FROM python:3.11-slim

WORKDIR /app

# Installer les dépendances système nécessaires à mysqlclient et netcat
RUN apt-get update && apt-get install -y \
    build-essential \
    pkg-config \
    default-libmysqlclient-dev \
    netcat-traditional \
    && rm -rf /var/lib/apt/lists/*

# Installer les dépendances Python
COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Copier le code du backend
COPY . .

EXPOSE 8000

# Attente MySQL + migration + lancement du serveur
CMD ["bash", "-c", "echo 'Waiting for MySQL to be ready...'; \
    while ! nc -z $MYSQL_HOST 3306; do sleep 2; done; \
    echo 'MySQL is up! Starting Django...'; \
    python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
