FROM python:3.11-slim

WORKDIR /app

# Installer les dépendances système (ex : psycopg2)
RUN apt-get update && apt-get install -y libpq-dev && rm -rf /var/lib/apt/lists/*

# Installer les dépendances Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier le code (sera monté par volume aussi)
COPY . .

EXPOSE 8000
